# Generated by Django 5.0.4 on 2024-04-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_customuser_address_customuser_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Image',
            field=models.ImageField(null=True, upload_to='picture'),
        ),
    ]
