# Generated by Django 5.0.4 on 2024-05-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='lasteducation',
            field=models.CharField(choices=[('ssc', 'SSC'), ('hsc', 'HSC'), ('honours', 'Honours')], max_length=100, null=True),
        ),
    ]
