# Generated by Django 5.0.4 on 2024-04-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='DifficultyLevel',
            field=models.CharField(choices=[('ealy_', 'Easy_'), ('medium_', 'Medium_'), ('hard_', 'Hard_')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='RecipeCategory',
            field=models.CharField(choices=[('break_fast', 'Break_Fast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='Tags',
            field=models.CharField(choices=[('vegetarian', 'Vegetarian'), ('nonvegetarian', 'Non_Vegetarian')], max_length=100, null=True),
        ),
    ]
