# Generated by Django 5.0.3 on 2024-03-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='firstcls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70)),
                ('Roll', models.CharField(max_length=70)),
                ('City', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Secondcls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Film', models.CharField(max_length=70)),
                ('Actor', models.CharField(max_length=70)),
                ('Director', models.CharField(max_length=70)),
            ],
        ),
    ]
