# Generated by Django 5.0.3 on 2024-03-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='thirdcls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie', models.CharField(max_length=40)),
                ('Release_Year', models.CharField(max_length=40)),
                ('Box_office', models.CharField(max_length=40)),
            ],
        ),
    ]
