# Generated by Django 5.0.3 on 2024-03-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_thirdcls'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='trachermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
            ],
        ),
    ]
