# Generated by Django 5.0.4 on 2024-04-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjobmodel',
            name='rename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
