# Generated by Django 5.0.4 on 2024-04-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='ProfilePicture',
            field=models.ImageField(null=True, upload_to='profile_picture'),
        ),
    ]
