# Generated by Django 4.2.5 on 2024-03-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='Roll',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='Department',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='FirstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='LastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='City',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
