# Generated by Django 5.0.3 on 2024-03-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mapptwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mtwofive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
                ('country', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='mtwofour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nametwo', models.CharField(max_length=50)),
                ('namethree', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='mtwothree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('two', models.IntegerField(max_length=50)),
                ('three', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='mtwotwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
