# Generated by Django 5.0.3 on 2024-04-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='PDF',
            field=models.FileField(null=True, upload_to='teacherpdf'),
        ),
    ]
