# Generated by Django 5.0.3 on 2024-03-19 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='depatment',
            new_name='department',
        ),
    ]
