# Generated by Django 5.0.4 on 2024-04-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50, null=True)),
                ('Address', models.CharField(max_length=50, null=True)),
                ('PhoneNumber', models.CharField(max_length=50, null=True)),
                ('EmailAddress', models.CharField(max_length=50, null=True)),
                ('CareerObject', models.CharField(max_length=50, null=True)),
                ('Picture', models.ImageField(upload_to='picture')),
                ('Degree', models.CharField(max_length=50, null=True)),
                ('Institution', models.CharField(max_length=50, null=True)),
                ('GraduationYear', models.CharField(max_length=50, null=True)),
                ('Company', models.CharField(max_length=50, null=True)),
                ('Position', models.CharField(max_length=50, null=True)),
                ('StartDate', models.CharField(max_length=50, null=True)),
                ('EndDate', models.CharField(max_length=50, null=True)),
                ('HardSkill', models.CharField(max_length=50, null=True)),
                ('SoftSkill', models.CharField(max_length=50, null=True)),
                ('Certifications', models.CharField(max_length=50, null=True)),
                ('Projects', models.CharField(max_length=50, null=True)),
                ('References', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
