# Generated by Django 5.0.3 on 2024-03-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Age', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teachermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Age', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=50)),
            ],
        ),
    ]
