# Generated by Django 5.0.4 on 2024-05-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seekerprofile',
            old_name='company_location',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='seekerprofile',
            old_name='company_name',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='seekerprofile',
            old_name='recruiter_name',
            new_name='skills',
        ),
    ]
