# Generated by Django 5.0.3 on 2024-04-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_rename_address_studentmodel_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='TeacherImage',
            field=models.ImageField(null=True, upload_to='media/Teacher_image'),
        ),
    ]
