# Generated by Django 5.0.3 on 2024-04-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_teachermodel_teacherimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='StdImage',
            field=models.ImageField(null=True, upload_to='meadia/student_image'),
        ),
    ]
