# Generated by Django 5.0.3 on 2024-04-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_studentmodel_stdimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctormodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100, null=True)),
                ('LastName', models.CharField(max_length=100, null=True)),
                ('DocImage', models.ImageField(null=True, upload_to='meadia/doctor_image')),
                ('Department', models.CharField(max_length=100, null=True)),
                ('City', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
